# Configuration Statique du Système de Routage
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: r1
              # uri: http://localhost:8081
              uri: lb://CUSTOMERSERVICE
              predicates:
                Path= /api/customers/**
            - id: r2
              #1 uri: http://localhost:8082
              uri: lb://INVENTORYSERVICE
              predicates:
                Path= /api/products/**
